import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers }  from "./providers";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import Background from "@/components/Background";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{colorScheme: 'light'}}>
      <body className={`${inter.className} bg-zinc-100 dark:bg-dark-blue h-full min-h-screen`}>
        <Providers>
          <NavBar />
            <div className="pageLanding">
              {children} 
            </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
